<a href="https://colab.research.google.com/github/Siva1212-genious/ML-Algorithms---ScikitLearn/blob/main/LogisticRegression_main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install legacy-cgi --quiet

In [2]:
!pip install opendatasets --quiet

In [3]:
import opendatasets as od

dataset_url = 'https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data'

od.download(dataset_url)

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: siva
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data


100%|██████████| 48.6k/48.6k [00:00<00:00, 42.5MB/s]

In [4]:
import os

data_set = './breast-cancer-wisconsin-data'

os.listdir(data_set)

['data.csv']

In [5]:
data = data_set + '/data.csv'

data

'./breast-cancer-wisconsin-data/data.csv'

In [6]:
import pandas as pd

raw_data = pd.read_csv(data)

raw_data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN


In [7]:
raw_data[1:50]

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
1,842517,M,20.570,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.070170,...,23.41,158.80,1956.0,0.12380,0.18660,0.24160,0.18600,0.2750,0.08902,NaN
2,84300903,M,19.690,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.127900,...,25.53,152.50,1709.0,0.14440,0.42450,0.45040,0.24300,0.3613,0.08758,NaN
3,84348301,M,11.420,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.105200,...,26.50,98.87,567.7,0.20980,0.86630,0.68690,0.25750,0.6638,0.17300,NaN
4,84358402,M,20.290,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.104300,...,16.67,152.20,1575.0,0.13740,0.20500,0.40000,0.16250,0.2364,0.07678,NaN
5,843786,M,12.450,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.080890,...,23.75,103.40,741.6,0.17910,0.52490,0.53550,0.17410,0.3985,0.12440,NaN
6,844359,M,18.250,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.074000,...,27.66,153.20,1606.0,0.14420,0.25760,0.37840,0.19320,0.3063,0.08368,NaN
7,84458202,M,13.710,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.059850,...,28.14,110.60,897.0,0.16540,0.36820,0.26780,0.15560,0.3196,0.11510,NaN
8,844981,M,13.000,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.093530,...,30.73,106.20,739.3,0.17030,0.54010,0.53900,0.20600,0.4378,0.10720,NaN
9,84501001,M,12.460,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.085430,...,40.68,97.65,711.4,0.18530,1.05800,1.10500,0.22100,0.4366,0.20750,NaN
10,845636,M,16.020,23.24,102.70,797.8,0.08206,0.06669,0.03299,0.033230,...,33.88,123.80,1150.0,0.11810,0.15510,0.14590,0.09975,0.2948,0.08452,NaN


In [8]:
raw_data.isna().sum()

,0
id,0
diagnosis,0
radius_mean,0
texture_mean,0
perimeter_mean,0
area_mean,0
smoothness_mean,0
compactness_mean,0
concavity_mean,0
concave points_mean,0


In [9]:
raw_data.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,NaN


In [10]:
#Now lets remove unusefull columns
raw_data.drop(columns = ['Unnamed: 32'], inplace = True)

In [11]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [12]:
#Now lets do the scalling for all the input columns using MinMaxScalar

In [13]:
#Lets first choose the numeric columns
import numpy as np

numeric_columns = raw_data.select_dtypes(include = np.number).columns.tolist()

In [14]:
numeric_columns

['id',
 'radius_mean',
 'texture_mean',
 'perimeter_mean',
 'area_mean',
 'smoothness_mean',
 'compactness_mean',
 'concavity_mean',
 'concave points_mean',
 'symmetry_mean',
 'fractal_dimension_mean',
 'radius_se',
 'texture_se',
 'perimeter_se',
 'area_se',
 'smoothness_se',
 'compactness_se',
 'concavity_se',
 'concave points_se',
 'symmetry_se',
 'fractal_dimension_se',
 'radius_worst',
 'texture_worst',
 'perimeter_worst',
 'area_worst',
 'smoothness_worst',
 'compactness_worst',
 'concavity_worst',
 'concave points_worst',
 'symmetry_worst',
 'fractal_dimension_worst']

In [15]:
numeric_columns = numeric_columns[1:]

In [16]:
numeric_columns

['radius_mean',
 'texture_mean',
 'perimeter_mean',
 'area_mean',
 'smoothness_mean',
 'compactness_mean',
 'concavity_mean',
 'concave points_mean',
 'symmetry_mean',
 'fractal_dimension_mean',
 'radius_se',
 'texture_se',
 'perimeter_se',
 'area_se',
 'smoothness_se',
 'compactness_se',
 'concavity_se',
 'concave points_se',
 'symmetry_se',
 'fractal_dimension_se',
 'radius_worst',
 'texture_worst',
 'perimeter_worst',
 'area_worst',
 'smoothness_worst',
 'compactness_worst',
 'concavity_worst',
 'concave points_worst',
 'symmetry_worst',
 'fractal_dimension_worst']

In [17]:
#Now Letus do the encoding for the 'object columns' i.e,. diagnosis

diagnosis_codes = {'B': 0, 'M': 1}

raw_data['diagnosis_codes'] = raw_data.diagnosis.map(diagnosis_codes)

In [18]:
cancer_no = raw_data[raw_data['diagnosis_codes'] == 0]

In [19]:
raw_data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,diagnosis_codes
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,1
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,1
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,1
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,1
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,1
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,1
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,1
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,1


In [20]:
#Now lets use the scalling for numeric columns

In [21]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

raw_data[numeric_columns] = scaler.fit_transform(raw_data[numeric_columns])

In [22]:
raw_data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,diagnosis_codes
0,842302,M,0.521037,0.022658,0.545989,0.363733,0.593753,0.792037,0.703140,0.731113,...,0.141525,0.668310,0.450698,0.601136,0.619292,0.568610,0.912027,0.598462,0.418864,1
1,842517,M,0.643144,0.272574,0.615783,0.501591,0.289880,0.181768,0.203608,0.348757,...,0.303571,0.539818,0.435214,0.347553,0.154563,0.192971,0.639175,0.233590,0.222878,1
2,84300903,M,0.601496,0.390260,0.595743,0.449417,0.514309,0.431017,0.462512,0.635686,...,0.360075,0.508442,0.374508,0.483590,0.385375,0.359744,0.835052,0.403706,0.213433,1
3,84348301,M,0.210090,0.360839,0.233501,0.102906,0.811321,0.811361,0.565604,0.522863,...,0.385928,0.241347,0.094008,0.915472,0.814012,0.548642,0.884880,1.000000,0.773711,1
4,84358402,M,0.629893,0.156578,0.630986,0.489290,0.430351,0.347893,0.463918,0.518390,...,0.123934,0.506948,0.341575,0.437364,0.172415,0.319489,0.558419,0.157500,0.142595,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,0.690000,0.428813,0.678668,0.566490,0.526948,0.296055,0.571462,0.690358,...,0.383262,0.576174,0.452664,0.461137,0.178527,0.328035,0.761512,0.097575,0.105667,1
565,926682,M,0.622320,0.626987,0.604036,0.474019,0.407782,0.257714,0.337395,0.486630,...,0.699094,0.520892,0.379915,0.300007,0.159997,0.256789,0.559450,0.198502,0.074315,1
566,926954,M,0.455251,0.621238,0.445788,0.303118,0.288165,0.254340,0.216753,0.263519,...,0.589019,0.379949,0.230731,0.282177,0.273705,0.271805,0.487285,0.128721,0.151909,1
567,927241,M,0.644564,0.663510,0.665538,0.475716,0.588336,0.790197,0.823336,0.755467,...,0.730277,0.668310,0.402035,0.619626,0.815758,0.749760,0.910653,0.497142,0.452315,1


In [23]:
raw_data.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,diagnosis_codes
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,3.037183e+07,0.338222,0.323965,0.332935,0.216920,0.394785,0.260601,0.208058,0.243137,0.379605,...,0.363998,0.283138,0.170906,0.404138,0.220212,0.217403,0.393836,0.263307,0.189596,0.372583
std,1.250206e+08,0.166787,0.145453,0.167915,0.149274,0.126967,0.161992,0.186785,0.192857,0.138456,...,0.163813,0.167352,0.139932,0.150779,0.152649,0.166633,0.225884,0.121954,0.118466,0.483918
min,8.670000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8.692180e+05,0.223342,0.218465,0.216847,0.117413,0.304595,0.139685,0.069260,0.100944,0.282323,...,0.241471,0.167837,0.081130,0.300007,0.116337,0.091454,0.223127,0.185098,0.107700,0.000000
50%,9.060240e+05,0.302381,0.308759,0.293345,0.172895,0.390358,0.224679,0.144189,0.166501,0.369697,...,0.356876,0.235320,0.123206,0.397081,0.179110,0.181070,0.343402,0.247782,0.163977,0.000000
75%,8.813129e+06,0.416442,0.408860,0.416765,0.271135,0.475490,0.340531,0.306232,0.367793,0.453030,...,0.471748,0.373475,0.220901,0.494156,0.302520,0.305831,0.554639,0.318155,0.242949,1.000000
max,9.113205e+08,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000


In [24]:
#Now first lets use Logestic regression model and after that we will use Decision Trees and Random Forest.

#we will split the train_data, test_data, validation_data

In [25]:
main_data = raw_data[numeric_columns]

In [26]:
main_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   radius_mean              569 non-null    float64
 1   texture_mean             569 non-null    float64
 2   perimeter_mean           569 non-null    float64
 3   area_mean                569 non-null    float64
 4   smoothness_mean          569 non-null    float64
 5   compactness_mean         569 non-null    float64
 6   concavity_mean           569 non-null    float64
 7   concave points_mean      569 non-null    float64
 8   symmetry_mean            569 non-null    float64
 9   fractal_dimension_mean   569 non-null    float64
 10  radius_se                569 non-null    float64
 11  texture_se               569 non-null    float64
 12  perimeter_se             569 non-null    float64
 13  area_se                  569 non-null    float64
 14  smoothness_se            5

In [27]:
target_data = raw_data['diagnosis_codes']

In [28]:
from sklearn.model_selection import train_test_split

train_val_data, test_data, train_val_target, test_target = train_test_split(raw_data, target_data, test_size = 0.2, random_state = 42)

train_data, val_data, train_target, val_target = train_test_split(train_val_data,train_val_target, test_size = 0.2, random_state = 42)

In [29]:
print(train_data.shape)
print(val_data.shape)
print(test_data.shape)
print(train_target.shape)

(364, 33)
(91, 33)
(114, 33)
(364,)


In [30]:
numeric_columns

['radius_mean',
 'texture_mean',
 'perimeter_mean',
 'area_mean',
 'smoothness_mean',
 'compactness_mean',
 'concavity_mean',
 'concave points_mean',
 'symmetry_mean',
 'fractal_dimension_mean',
 'radius_se',
 'texture_se',
 'perimeter_se',
 'area_se',
 'smoothness_se',
 'compactness_se',
 'concavity_se',
 'concave points_se',
 'symmetry_se',
 'fractal_dimension_se',
 'radius_worst',
 'texture_worst',
 'perimeter_worst',
 'area_worst',
 'smoothness_worst',
 'compactness_worst',
 'concavity_worst',
 'concave points_worst',
 'symmetry_worst',
 'fractal_dimension_worst']

In [31]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(train_data[numeric_columns], train_target)

LogisticRegression()

In [32]:
train_prediction = model.predict(train_data[numeric_columns])

In [33]:
train_prediction

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,

In [34]:
#Now Lets calculate the train probability for train_data, val_data

In [35]:
model.classes_

array([0, 1])

In [36]:
import numpy as np

prediction_prob = model.predict_proba(train_data[numeric_columns])

np.set_printoptions(suppress = True)

print(prediction_prob)

[[0.63423021 0.36576979]
 [0.00428017 0.99571983]
 [0.78633558 0.21366442]
 [0.92386138 0.07613862]
 [0.94151581 0.05848419]
 [0.9436627  0.0563373 ]
 [0.01026252 0.98973748]
 [0.0414525  0.9585475 ]
 [0.91097955 0.08902045]
 [0.96637942 0.03362058]
 [0.87696453 0.12303547]
 [0.8408842  0.1591158 ]
 [0.04040187 0.95959813]
 [0.00261976 0.99738024]
 [0.06831239 0.93168761]
 [0.75094377 0.24905623]
 [0.90680626 0.09319374]
 [0.97944882 0.02055118]
 [0.00029539 0.99970461]
 [0.03289994 0.96710006]
 [0.99248224 0.00751776]
 [0.6514736  0.3485264 ]
 [0.99542146 0.00457854]
 [0.98622969 0.01377031]
 [0.13169822 0.86830178]
 [0.00221271 0.99778729]
 [0.95638308 0.04361692]
 [0.96873369 0.03126631]
 [0.98995121 0.01004879]
 [0.91120685 0.08879315]
 [0.91451519 0.08548481]
 [0.50168471 0.49831529]
 [0.94860683 0.05139317]
 [0.95315665 0.04684335]
 [0.13893376 0.86106624]
 [0.90726577 0.09273423]
 [0.73702706 0.26297294]
 [0.93802844 0.06197156]
 [0.09305897 0.90694103]
 [0.97405048 0.02594952]


In [37]:
#Now we need to check the accuracy of the predicted and actual data for training data

In [38]:
from sklearn.metrics import accuracy_score

train_data_accuracy = accuracy_score(train_target, train_prediction, normalize=True)

print("Accuracy: ", train_data_accuracy*100)

Accuracy:  97.25274725274726


In [39]:
#So, our training data accuracy is 97.25%
#Now we will check the confusion matrix for this training data.

In [40]:
############################## IMPORTANT ###################################################################
#We Need to use CONFUSION MATRIX to identify, where our model is actually getting failed.
#This CONFUSION MATRIX defines, where our model is actually getting failed.
#It gives us 1.TRUE NEGATIVE(TN), 2. TRUE POSITIVE(TP), 3. FALSE NEGATIVE(FN), 4. FALSE POSITIVE(FP)
# With This Confusion matrix we can extract 1.ACCURACY 2. PRECISION 3. RECALL 4.F1-SCORE
#1.ACCURACY = (TN + TP)/(TN + TP+ FN+ FP) #
#2. PRECISION = TP/(TP + FP) # Of everything the model predicted positive, how many were actually positive?
#3. RECALL = TP/(TP + FN) # Of everything that was actually positive, how many did the model find?
#4. F1-SCORE = F1 = 2 × (Precision × Recall) / (Precision + Recall) # Combines precision and recall:

In [41]:
#NOW lets calculate the CONFUSION MATRIX for the training data.

In [42]:
from sklearn.metrics import confusion_matrix

confusion_mat = confusion_matrix(train_target, train_prediction)

print(confusion_mat)

[[231   0]
 [ 10 123]]


In [43]:
############################################### IMPORTANT ###################################################
# Now we can find TP, FP, TN, FN from this confusion matrix and we can find accuracy, precision, recall, f1-score

In [44]:
TN, FP, FN, TP = confusion_matrix(train_target, train_prediction).ravel()

print("True Negative:", TN)
print("False Positive:", FP)
print("False Negative:", FN)
print("True Positive:", TP)

True Negative: 231
False Positive: 0
False Negative: 10
True Positive: 123


In [45]:
#######################IMPORTANT###################################
#nOW LET US TEST OUR MODEL ON VAL_DATA

In [46]:
validation_prediction = model.predict(val_data[numeric_columns])

validation_prediction

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0])

In [47]:
val_target

,diagnosis_codes
95,1
93,0
401,0
345,0
194,1
...,...
71,0
16,1
346,0
149,0


In [48]:
#Now lets calculate accuracy using function

from sklearn.metrics import accuracy_score

val_data_accuracy = accuracy_score(val_target, validation_prediction)

print("validation_Accuracy: ", val_data_accuracy * 100)

validation_Accuracy:  94.5054945054945


In [49]:
#Lets create the confusion matrix and check the accuracy rate.

In [50]:
from sklearn.metrics import confusion_matrix

val_confusion_matrix = confusion_matrix(val_target, validation_prediction)

print(val_confusion_matrix)

[[53  2]
 [ 3 33]]


In [51]:
TN, FP, FN, TP = confusion_matrix(val_target, validation_prediction).ravel()

print("True Negative:", TN)
print("False Positive:", FP)
print("False Negative:", FN)
print("True Positive:", TP)

True Negative: 53
False Positive: 2
False Negative: 3
True Positive: 33


In [52]:
#I think the accuracy is good in between training data and validation data.
#Now we will test our model on the test_data

In [53]:
Test_prediction = model.predict(test_data[numeric_columns])

Test_prediction

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

In [54]:
test_target

,diagnosis_codes
204,0
70,1
131,1
431,0
540,0
...,...
486,0
75,1
249,0
238,0


In [55]:
# Now, we will find the accuracy score and confusion matrix

In [56]:
test_prediction_accuracy = accuracy_score(test_target, Test_prediction)

print("Test_prediction_accuracy: ", test_prediction_accuracy*100)

Test_prediction_accuracy:  97.36842105263158


In [57]:
#We will find confusion matrix

Test_confusion_matrix = confusion_matrix(test_target, Test_prediction)

print(Test_confusion_matrix)

[[70  1]
 [ 2 41]]


In [58]:
TN, FP, FN, TP = confusion_matrix(test_target, Test_prediction).ravel()

print("True Negative:", TN)
print("False Positive:", FP)
print("False Negative:", FN)
print("True Positive:", TP)

True Negative: 70
False Positive: 1
False Negative: 2
True Positive: 41


In [59]:
########################################## CLOSE OF LOGESTIC REGRESSION ##################################
#OUR ACCURACY SCORES IS VERY GOOD. OUR MODEL IS PERFORMING EXTRODINARILY

In [60]:
#lETS TEST BY GIVING ONE SINGLE ROW
import pandas as pd

def predict_random_data(single_row):
  input_data = pd.DataFrame([single_row])
  input_data[numeric_columns] = scaler.transform(input_data[numeric_columns])
  X_input = input_data[numeric_columns]

  new_prediction = model.predict(X_input)[0]
  new_pred_prob = model.predict_proba(X_input)[0][list(model.classes_).index(new_prediction)]


  return new_prediction, new_pred_prob


In [61]:
#JUST FINDING THE DATA TO INSERT IN A SINGLE ROW(Just Learn)
import pandas as pd

daw_data = pd.read_csv(data)

daw_data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN


In [62]:
import pandas as pd

single_row = {
               'diagnosis':'M',
               'radius_mean' :17.99,
               'texture_mean': 10.38,
               'perimeter_mean':122.8 ,
               'area_mean': 1001.0 ,
               'smoothness_mean':0.1184,
               'compactness_mean': 0.2776,
               'concavity_mean': 0.3001,
               'concave points_mean': 0.1471,
               'symmetry_mean':0.2419,
               'fractal_dimension_mean':0.07871,
               'radius_se':1.095,
               'texture_se':0.9053,
               'perimeter_se':8.589,
               'area_se':153.4,
               'smoothness_se':0.006399,
               'compactness_se':0.04904,
               'concavity_se':0.05373,
               'concave points_se' : 0.01587,
               'symmetry_se': 0.03003,
               'fractal_dimension_se': 0.006193,
               'radius_worst': 25.380,
               'texture_worst':17.33,
               'perimeter_worst':184.60,
               'area_worst': 2019.0,
               'smoothness_worst':0.16220,
               'compactness_worst':0.66560,
               'concavity_worst': 0.7119,
               'concave points_worst': 0.2654,
               'symmetry_worst':0.4601,
               'fractal_dimension_worst':0.19890
}

predict_random_data(single_row)

(np.int64(1), np.float64(0.9981236930506258))

In [63]:
import pandas as pd

single_row = {
    'diagnosis': 'B',
    'radius_mean': 13.54,
    'texture_mean': 14.36,
    'perimeter_mean': 87.46,
    'area_mean': 566.3,
    'smoothness_mean': 0.09779,
    'compactness_mean': 0.08129,
    'concavity_mean': 0.06664,
    'concave points_mean': 0.04781,
    'symmetry_mean': 0.1885,
    'fractal_dimension_mean': 0.05766,
    'radius_se': 0.2699,
    'texture_se': 0.7886,
    'perimeter_se': 2.058,
    'area_se': 23.56,
    'smoothness_se': 0.008462,
    'compactness_se': 0.0146,
    'concavity_se': 0.02387,
    'concave points_se': 0.01315,
    'symmetry_se': 0.0198,
    'fractal_dimension_se': 0.0023,
    'radius_worst': 15.11,
    'texture_worst': 19.26,
    'perimeter_worst': 99.7,
    'area_worst': 711.2,
    'smoothness_worst': 0.144,
    'compactness_worst': 0.1773,
    'concavity_worst': 0.239,
    'concave points_worst': 0.1288,
    'symmetry_worst': 0.2977,
    'fractal_dimension_worst': 0.07259
}

predict_random_data(single_row)

(np.int64(0), np.float64(0.8329711084639182))

In [64]:
import pandas as pd

single_row = {
    'diagnosis': 'M',
    'radius_mean': 18.25,
    'texture_mean': 19.98,
    'perimeter_mean': 119.6,
    'area_mean': 1040.0,
    'smoothness_mean': 0.09463,
    'compactness_mean': 0.109,
    'concavity_mean': 0.1127,
    'concave points_mean': 0.074,
    'symmetry_mean': 0.1794,
    'fractal_dimension_mean': 0.05742,
    'radius_se': 0.4467,
    'texture_se': 0.7732,
    'perimeter_se': 3.18,
    'area_se': 53.91,
    'smoothness_se': 0.004314,
    'compactness_se': 0.01382,
    'concavity_se': 0.02254,
    'concave points_se': 0.01039,
    'symmetry_se': 0.01369,
    'fractal_dimension_se': 0.002179,
    'radius_worst': 22.88,
    'texture_worst': 27.66,
    'perimeter_worst': 153.2,
    'area_worst': 1606.0,
    'smoothness_worst': 0.1442,
    'compactness_worst': 0.2576,
    'concavity_worst': 0.3784,
    'concave points_worst': 0.1932,
    'symmetry_worst': 0.3063,
    'fractal_dimension_worst': 0.08368
}

predict_random_data(single_row)

(np.int64(1), np.float64(0.948924597428639))

In [65]:
import pandas as pd

single_row = {
    'diagnosis': 'B',
    'radius_mean': 11.52, 'texture_mean': 18.45, 'perimeter_mean': 73.80, 'area_mean': 407.5,
    'smoothness_mean': 0.09345, 'compactness_mean': 0.05924, 'concavity_mean': 0.02741, 'concave points_mean': 0.02058,
    'symmetry_mean': 0.1619, 'fractal_dimension_mean': 0.06201, 'radius_se': 0.2543, 'texture_se': 0.9542,
    'perimeter_se': 1.832, 'area_se': 18.24, 'smoothness_se': 0.006241, 'compactness_se': 0.01152,
    'concavity_se': 0.01524, 'concave points_se': 0.008432, 'symmetry_se': 0.01892, 'fractal_dimension_se': 0.002143,
    'radius_worst': 12.84, 'texture_worst': 24.15, 'perimeter_worst': 83.42, 'area_worst': 503.4,
    'smoothness_worst': 0.1243, 'compactness_worst': 0.1154, 'concavity_worst': 0.0924, 'concave points_worst': 0.05632,
    'symmetry_worst': 0.2435, 'fractal_dimension_worst': 0.07123

}

predict_random_data(single_row)

(np.int64(0), np.float64(0.9731300243465366))

In [66]:
import pandas as pd

single_row = {
    'diagnosis': 'M',
    'radius_mean': 20.15, 'texture_mean': 22.34, 'perimeter_mean': 133.20, 'area_mean': 1264.0,
    'smoothness_mean': 0.10842, 'compactness_mean': 0.16450, 'concavity_mean': 0.21450, 'concave points_mean': 0.12450,
    'symmetry_mean': 0.1984, 'fractal_dimension_mean': 0.06124, 'radius_se': 0.6342, 'texture_se': 1.1523,
    'perimeter_se': 4.562, 'area_se': 78.43, 'smoothness_se': 0.005842, 'compactness_se': 0.03542,
    'concavity_se': 0.04852, 'concave points_se': 0.01845, 'symmetry_se': 0.02241, 'fractal_dimension_se': 0.003945,
    'radius_worst': 25.42, 'texture_worst': 30.12, 'perimeter_worst': 172.40, 'area_worst': 1984.0,
    'smoothness_worst': 0.1523, 'compactness_worst': 0.4124, 'concavity_worst': 0.5432, 'concave points_worst': 0.2241,
    'symmetry_worst': 0.3421, 'fractal_dimension_worst': 0.09842

}

predict_random_data(single_row)

(np.int64(1), np.float64(0.9971598890587472))

In [ ]:
#Now let us do this in DECISION TREE AND RANDOM FOREST.

In [67]:
raw_data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,diagnosis_codes
0,842302,M,0.521037,0.022658,0.545989,0.363733,0.593753,0.792037,0.703140,0.731113,...,0.141525,0.668310,0.450698,0.601136,0.619292,0.568610,0.912027,0.598462,0.418864,1
1,842517,M,0.643144,0.272574,0.615783,0.501591,0.289880,0.181768,0.203608,0.348757,...,0.303571,0.539818,0.435214,0.347553,0.154563,0.192971,0.639175,0.233590,0.222878,1
2,84300903,M,0.601496,0.390260,0.595743,0.449417,0.514309,0.431017,0.462512,0.635686,...,0.360075,0.508442,0.374508,0.483590,0.385375,0.359744,0.835052,0.403706,0.213433,1
3,84348301,M,0.210090,0.360839,0.233501,0.102906,0.811321,0.811361,0.565604,0.522863,...,0.385928,0.241347,0.094008,0.915472,0.814012,0.548642,0.884880,1.000000,0.773711,1
4,84358402,M,0.629893,0.156578,0.630986,0.489290,0.430351,0.347893,0.463918,0.518390,...,0.123934,0.506948,0.341575,0.437364,0.172415,0.319489,0.558419,0.157500,0.142595,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,0.690000,0.428813,0.678668,0.566490,0.526948,0.296055,0.571462,0.690358,...,0.383262,0.576174,0.452664,0.461137,0.178527,0.328035,0.761512,0.097575,0.105667,1
565,926682,M,0.622320,0.626987,0.604036,0.474019,0.407782,0.257714,0.337395,0.486630,...,0.699094,0.520892,0.379915,0.300007,0.159997,0.256789,0.559450,0.198502,0.074315,1
566,926954,M,0.455251,0.621238,0.445788,0.303118,0.288165,0.254340,0.216753,0.263519,...,0.589019,0.379949,0.230731,0.282177,0.273705,0.271805,0.487285,0.128721,0.151909,1
567,927241,M,0.644564,0.663510,0.665538,0.475716,0.588336,0.790197,0.823336,0.755467,...,0.730277,0.668310,0.402035,0.619626,0.815758,0.749760,0.910653,0.497142,0.452315,1
